// Levels 14-100: the original RoboZZle campaign by Igor Ostrovsky and early
// contributors, sourced from the community-maintained archive at
// https://github.com/lostmsu/RoboZZle.LevelArchive (levels.xml), which mirrors
// the puzzle database from https://robozzle.com/. Level numbers are the
// original RoboZZle level IDs, unchanged. Levels 1-13 do not exist in this
// archive -- they were already gone from the live site by the time this
// archive was made (June 2024), so they are not included here.
export interface RobozzleLevel {
  id: number;
  title: string;
  about: string;
  author: string | null;
  items: string[];
  colors: string[];
  robotRow: number;
  robotCol: number;
  robotDir: number;
  subLengths: number[];
}

export const levels: RobozzleLevel[] = [
  {
    id: 14,
    title: "Can you reach the stars?",
    about: "This puzzle is dedicated to those that enjoy bad puns.",
    author: "igoro",
    items: ["####...#######", "..#..*....#...", "....*.*.*...*.", ".*.*.*........", ".........**.*.", "..**..........", ".*.....*....*.", "...###...##...", "######.*.#####", "######...#####"],
    colors: ["RRRRRRRRRRRRRR", "RRRRRBRRRRRRRR", "BRRRBBBRBRRRBR", "BBRBBBBBBBRBBB", "BBBBBRBBBBBBBB", "BBBBRRBBBRRBBB", "BBRRRRRBRRRRBR", "RRRRRRRBRRRRRR", "RRRRRRRBRRRRRR", "RRRRRRRRRRRRRR"],
    robotRow: 7,
    robotCol: 0,
    robotDir: 3,
    subLengths: [10, 2, 2, 0, 0],
  },
  {
    id: 15,
    title: "The star-studded path III",
    about: "Can you do it with just six (or even fewer) commands?",
    author: "igoro",
    items: ["####...#...#", "#...***.***.", ".****.***.*.", ".*........*.", ".********.*.", "#.......*.*.", "#######.*.*.", "##...##.*.*.", "#.***.#.*.*.", ".**.*.....*.", ".*..*******.", "...........#"],
    colors: ["RRRRBBBRBBBR", "RBBBRRRBRRRB", "BRRRRBRRRBRB", "BRBBBBBBBBRB", "BRRRRRRRRBRB", "RBBBBBBBRBRB", "RRRRRRRBRBRB", "RRBBBRRBRBRB", "RBRRRBRBRBRB", "BRRBRBBBBBRB", "BRBBRRRRRRRB", "BRBBBBBBBBBR"],
    robotRow: 11,
    robotCol: 1,
    robotDir: 3,
    subLengths: [6, 0, 0, 0, 0],
  },
  {
    id: 16,
    title: "The star-studded path II",
    about: "",
    author: "igoro",
    items: ["####...#...#", "#...***.***.", ".****.***.*.", ".*........*.", ".********.*.", "#.......*.*.", "#######.*.*.", "##...##.*.*.", "#.***.#.*.*.", ".**.*.....*.", ".*..*******.", "...........#"],
    colors: ["RRRRBBBRBBBR", "RBBBRRRBRRRB", "BRRRRBRRRBRB", "BRBBBBBBBBRB", "BRRRRRRRRBRB", "RBBBBBBBRBRB", "RRRRRRRBRBRB", "RRBBBRRBRBRB", "RBRRRBRBRBRB", "BRRBRBBBBBRB", "BRBBRRRRRRRB", "BRBBBBBBBBBR"],
    robotRow: 11,
    robotCol: 1,
    robotDir: 3,
    subLengths: [6, 6, 6, 0, 0],
  },
  {
    id: 17,
    title: "The star-studded path I",
    about: "",
    author: "igoro",
    items: ["####...#...#", "#...***.***.", ".****.***.*.", ".*........*.", ".*........*.", ".*******..*.", "#......*..*.", "##...####.*.", "..***.###.*.", ".**.*.....*.", ".*..*******.", "...........#"],
    colors: ["RRRRGGGRGGGR", "RGGGRRRGRRRG", "GRRRRBRRRBRG", "GRBBBBBBBBRG", "GRBBBBBBBBRG", "GRRRRRRRBBRG", "RGGGGGGRBBRG", "RRBBBRRRRBRG", "BBRRRBRRRBRG", "BRRGRBBBBBRG", "BRGGRRRRRRRG", "BRGGGGGGGGGR"],
    robotRow: 11,
    robotCol: 1,
    robotDir: 3,
    subLengths: [10, 10, 10, 0, 0],
  },
  {
    id: 18,
    title: "There can be more than one (solution)",
    about: "",
    author: "igoro",
    items: [".........", "*..**.**.", ".***.*..*", "*..*..**.", "**..*.*.*", "........."],
    colors: ["RRRRRRRRR", "GBGBGBGBG", "BGBGBGBGB", "GBGBGBGBG", "BGBGBGBGB", "RRRRRRRRR"],
    robotRow: 1,
    robotCol: 8,
    robotDir: 1,
    subLengths: [10, 10, 0, 0, 0],
  },
  {
    id: 19,
    title: "Red loop",
    about: "",
    author: "igoro",
    items: ["...#####...", "..********.", ".*#######*.", "#*#######*#", "#*#######*#", "#*#######*#", "#*#######*#", ".*#######*.", ".*********.", "...#####..."],
    colors: ["BBBRRRRRBBB", "BRRRRRRRRRB", "BRRRRRRRRRB", "RRRRRRRRRRR", "RRRRRRRRRRR", "RRRRRRRRRRR", "RRRRRRRRRRR", "BRRRRRRRRRB", "BRRRRRRRRRB", "BBBRRRRRBBB"],
    robotRow: 1,
    robotCol: 1,
    robotDir: 0,
    subLengths: [5, 0, 0, 0, 0],
  },
  {
    id: 20,
    title: "Spiral to victory",
    about: "",
    author: "igoro",
    items: ["............", ".##########.", ".#........#.", ".#.######.#.", ".#.#....#.#.", ".#.#.##.#.#.", ".#.#.#..#.#.", ".#.#.####.#.", ".#.#......#.", ".#.########.", "*#.........."],
    colors: ["BRRRRRRRRRRR", "BRRRRRRRRRRB", "BRGRRRRRRRRB", "BRGRRRRRRGRB", "BRGRBRRRRGRB", "BRGRBRRBRGRB", "BRGRBRRBRGRB", "BRGRBRRRRGRB", "BRGRRRRRRGRB", "BRGRRRRRRRRB", "BRRRRRRRRRRB"],
    robotRow: 6,
    robotCol: 6,
    robotDir: 0,
    subLengths: [5, 5, 5, 0, 0],
  },
  {
    id: 21,
    title: "Strange shape",
    about: "",
    author: "igoro",
    items: ["###*###", "##***##", "#*#.#*#", "**...**", "#*#.#*#", "###.###", "#*#.#*#", "**...**", "#*#.#*#", "##***##", "###*###"],
    colors: ["RRRBRRR", "RRBBBRR", "RBRBRBR", "BBBBBBB", "RBRBRBR", "RRRBRRR", "RBRBRBR", "BBBBBBB", "RBRBRBR", "RRBBBRR", "RRRBRRR"],
    robotRow: 5,
    robotCol: 3,
    robotDir: 1,
    subLengths: [5, 10, 10, 10, 0],
  },
  {
    id: 22,
    title: "Diamond",
    about: "",
    author: "igoro",
    items: ["####*", "###**", "##***", "#****", "*****", "*****", "****#", "***##", "**###", ".####"],
    colors: ["RRRRB", "RRRBB", "RRBBB", "RBBBB", "BBBBB", "BBBBB", "BBBBR", "BBBRR", "BBRRR", "BRRRR"],
    robotRow: 9,
    robotCol: 0,
    robotDir: 3,
    subLengths: [10, 5, 0, 0, 0],
  },
  {
    id: 23,
    title: "Two stripes",
    about: "There is a short solution.",
    author: "igoro",
    items: ["..........", "*.*.*.*...", ".*.*.*.*..", "..*.*.*.*.", "...*.*.*.*", ".........."],
    colors: ["GGGGGGGGGG", "BBBBBBBBBB", "BBBBBBBBBB", "BBBBBBBBBB", "BBBBBBBBBB", "RRRRRRRRRR"],
    robotRow: 2,
    robotCol: 0,
    robotDir: 3,
    subLengths: [4, 0, 0, 0, 0],
  },
  {
    id: 24,
    title: "Two functions",
    about: "",
    author: null,
    items: ["########.*", "#######..#", "######..##", "#####..###", "####..####", "###..#####", "##..######", "#..#######", "..########", ".#########"],
    colors: ["RRRRRRRRBB", "RRRRRRRBBR", "RRRRRRBBRR", "RRRRRBBRRR", "RRRRBBRRRR", "RRRBBRRRRR", "RRBBRRRRRR", "RBBRRRRRRR", "BBRRRRRRRR", "BRRRRRRRRR"],
    robotRow: 9,
    robotCol: 0,
    robotDir: 3,
    subLengths: [3, 3, 0, 0, 0],
  },
  {
    id: 25,
    title: "A window",
    about: " ",
    author: null,
    items: ["******", "*#**#*", "**.***", "******", "*#**#*", "******"],
    colors: ["BBBBBB", "BRBBRB", "BBBBBB", "BBBBBB", "BRBBRB", "BBBBBB"],
    robotRow: 2,
    robotCol: 2,
    robotDir: 3,
    subLengths: [4, 4, 4, 0, 0],
  },
  {
    id: 26,
    title: "Eight",
    about: "",
    author: null,
    items: ["*****", "*#*#*", "****."],
    colors: ["BBBBB", "BRBRB", "BBBBB"],
    robotRow: 2,
    robotCol: 4,
    robotDir: 3,
    subLengths: [10, 10, 10, 0, 0],
  },
  {
    id: 27,
    title: "Stairs",
    about: "",
    author: null,
    items: ["#########**", "########**#", "#######**##", "######**###", "#####**####", "####**#####", "###**######", "##**#######", "#**########", ".*#########"],
    colors: ["RRRRRRRRRBB", "RRRRRRRRBBR", "RRRRRRRBBRR", "RRRRRRBBRRR", "RRRRRBBRRRR", "RRRRBBRRRRR", "RRRBBRRRRRR", "RRBBRRRRRRR", "RBBRRRRRRRR", "BBRRRRRRRRR"],
    robotRow: 9,
    robotCol: 0,
    robotDir: 0,
    subLengths: [10, 0, 0, 0, 0],
  },
  {
    id: 28,
    title: "A twisty path",
    about: "Complex path from simple program",
    author: null,
    items: ["#**######", "#*******#", "********#", "*********", "#********", "#***.***#", "#*******#", "#******##"],
    colors: ["RBBRRRRRR", "RGRGGGGBR", "RGRRRRRBR", "RRRGGRRGB", "RBBGRBRGB", "RGRRBBRBR", "RGRRRRRBR", "RBBBBBBRR"],
    robotRow: 5,
    robotCol: 4,
    robotDir: 1,
    subLengths: [4, 0, 0, 0, 0],
  },
  {
    id: 29,
    title: "Space Invader",
    about: "Do the color's help?",
    author: null,
    items: ["............", "..###..###..", ".#********#.", ".#*#****#*#.", ".#********#.", "..***.****..", "..********..", ".#********#.", ".#*#****#*#.", ".#********#.", "..###..###.."],
    colors: ["RRRRRRRRRRRR", "RRRRRRRRRRRR", "RRBBBBBBBBRR", "RRBRBBBBRBRR", "RRBBBBBBBBRR", "RGBBBBBBBBGR", "RGBBBBBBBBGR", "RRBBBBBBBBRR", "RRBRBBBBRBRR", "RRBBBBBBBBRR", "RRRRRRRRRRRR"],
    robotRow: 5,
    robotCol: 5,
    robotDir: 3,
    subLengths: [5, 6, 4, 0, 0],
  },
  {
    id: 31,
    title: "Holiday stripe",
    about: "Essey's first puzzle attempt",
    author: "essey",
    items: ["...........", ".*.*...*.*.", "...........", ".*.*...*..*", ".........*.", ".....*....*", "...........", ".*.*..*.**.", "..........*", "...*.......", "..........."],
    colors: ["RRRRRRRRRRR", "RBRBBRRBRBR", "BBRBBRBBBBR", "BBBBBRBBBBB", "BBBBBBBBBBB", "BBBBBBBBBBB", "GRGRGRGRGRG", "BBBBBBBBBBB", "RBRBRBRBBRB", "RRRBRRRRBRR", "RRRRRRRRRRR"],
    robotRow: 10,
    robotCol: 0,
    robotDir: 3,
    subLengths: [10, 3, 3, 3, 3],
  },
  {
    id: 32,
    title: "Star-studded path IV",
    about: "Another interesting variant of the puzzle.",
    author: "igoro",
    items: ["#..............#", ".**************.", ".*............*.", ".*.##########.*.", ".*.*****#####.*.", ".*.*......###.*.", ".*.*.##.*.###.*.", ".*.*....*.###.*.", ".*.*.****.###.*.", ".*.*.*....***.*.", ".***.******.***.", "#...#......#...#"],
    colors: ["RBGGGGBBBGGGBBBR", "BRRRRRRRRRRRRRRG", "BRGBBBGGGBBBGGRB", "GRBRRRRRRRRRRGRB", "GRBRRRRRRRRRRBRB", "GRBRBBBBBGRRRBRG", "BRGRBRRRRGRRRBRG", "BRGRBBBBRGRRRGRG", "BRGRBRRRRBRRRGRB", "GRBRBRGGGBRRRGRB", "GRRRBRRRRRRBRRRB", "RGBBRGGGBBBRGGGR"],
    robotRow: 6,
    robotCol: 7,
    robotDir: 0,
    subLengths: [5, 0, 0, 0, 0],
  },
  {
    id: 33,
    title: "Can you count?",
    about: "",
    author: "igoro",
    items: ["....*######", "..*########", "......*####", "....*######", "..........*", "....*######", "......*####", "..*########", "....*######"],
    colors: ["RGGBBRRRRRR", "RGBRRRRRRRR", "RGGGBBBRRRR", "RGGBBRRRRRR", "RGGGGGBBBBB", "RGGBBRRRRRR", "RGGGBBBRRRR", "RGBRRRRRRRR", "RGGBBRRRRRR"],
    robotRow: 0,
    robotCol: 1,
    robotDir: 0,
    subLengths: [10, 5, 5, 0, 0],
  },
  {
    id: 34,
    title: "Don't fall off the spiral",
    about: "",
    author: "igoro",
    items: ["............", ".##########.", ".#........#.", ".#.######.#.", ".#.#....#.#.", ".#.#.##.#.#.", ".#.#.#..#.#.", ".#.#.####.#.", ".#.#......#.", ".#.########.", "*#.........."],
    colors: ["RBBBBBBBBBBR", "RRRRRRRRRRRR", "RRRBBBBBBRRR", "RRRRRRRRRRRR", "RRRRRBBRRRRR", "RRRRRRRRRRRR", "RRRRRRBRRRRR", "RRRRRRRRRRRR", "RRRRRBBBBRRR", "RRRRRRRRRRRR", "RRRBBBBBBBBR"],
    robotRow: 6,
    robotCol: 6,
    robotDir: 0,
    subLengths: [5, 5, 0, 0, 0],
  },
  {
    id: 35,
    title: "Kind of math...",
    about: "Does not quite fit.",
    author: "igoro",
    items: ["########***#####", "########*#*#####", "######***#***###", "######*#####*###", "####***#####***#", "####*#########*#", "##*****#####****", "##*#*#*#####*#*#", ".**#***#####***#"],
    colors: ["RRRRRRRRBBBRRRRR", "RRRRRRRRBRBRRRRR", "RRRRRRBBBRBBBRRR", "RRRRRRBRRRRRBRRR", "RRRRBBBRRRRRBBBR", "RRRRBRRRRRRRRRBR", "RRBBBBBRRRRRBBBB", "RRBRBRBRRRRRBRBR", "BBBRBBBRRRRRBBBR"],
    robotRow: 8,
    robotCol: 0,
    robotDir: 0,
    subLengths: [10, 10, 2, 0, 0],
  },
  {
    id: 36,
    title: "Explore the world",
    about: "It's small... and you have the \"Fast\" button",
    author: "igoro",
    items: ["***#**#", "*******", "*******", "**##**#", "**##***", "*******", ".******"],
    colors: ["RRRRRRR", "BBBRBBR", "BBBBBBR", "BRRRRRR", "BRRRBBR", "BBRRBBR", "BBBBBBR"],
    robotRow: 6,
    robotCol: 0,
    robotDir: 0,
    subLengths: [10, 5, 0, 0, 0],
  },
  {
    id: 37,
    title: "On the edge",
    about: "",
    author: "igoro",
    items: ["##*#######*##", "##.#######.##", "#*.*#####*.*#", "#...#####...#", "#...#####...#", "*...**#**...*", "......*......", ".............", "............."],
    colors: ["RRRRRRRRRRRRR", "RRBRRRRRRRBRR", "RRBRRRRRRRBRR", "RBBBRRRRRBBBR", "RBBBRRRRRBBBR", "RBBBRRRRRBBBR", "BBBBBBRBBBBBB", "BBBBBBBBBBBBB", "BBBBBBBBBBBBB"],
    robotRow: 8,
    robotCol: 0,
    robotDir: 3,
    subLengths: [10, 10, 0, 0, 0],
  },
  {
    id: 38,
    title: "The chambers",
    about: " ",
    author: "igoro",
    items: ["......########", ".****.########", "....*.########", "###.*.####....", "....*......**.", ".**.*********.", ".*****.*......", ".**.*********.", "....*......**.", "###.*.####....", "###.*.########", "###...########"],
    colors: ["RRRRRRRRRRRRRR", "RBBBBRRRRRRRRR", "RRRRBRRRRRRRRR", "RRRRBRRRRRRRRR", "RRRRBRRRRRRBBR", "RBBRBBBBBBBBBR", "RBBBBBBBRRRRRR", "RBBRBBBBBBBBBR", "RRRRBRRRRRRBBR", "RRRRBRRRRRRRRR", "RRRRBRRRRRRRRR", "RRRRRRRRRRRRRR"],
    robotRow: 6,
    robotCol: 6,
    robotDir: 0,
    subLengths: [10, 10, 5, 0, 0],
  },
  {
    id: 39,
    title: "Smart reuse",
    about: "",
    author: "igoro",
    items: ["####...", "####.#.", "##...#*", "##.####", "##...##", "####.##", "##...##", "##.####", "...####"],
    colors: ["RRRRBBB", "RRRRBRB", "RRBBBRB", "RRBRRRR", "RRBBBRR", "RRRRBRR", "RRBBBRR", "RRBRRRR", "BBBRRRR"],
    robotRow: 8,
    robotCol: 0,
    robotDir: 0,
    subLengths: [10, 3, 3, 0, 0],
  },
  {
    id: 40,
    title: "Up and down the stairs",
    about: "",
    author: "igoro",
    items: ["#####.*", "####..#", "##...##", "#..####", "*.#####"],
    colors: ["RRRRRBB", "RRRRBBR", "RRBRBRR", "RBBRRRR", "BBRRRRR"],
    robotRow: 2,
    robotCol: 3,
    robotDir: 0,
    subLengths: [5, 10, 0, 0, 0],
  },
  {
    id: 41,
    title: "The windmill",
    about: "",
    author: "poiuy",
    items: ["#####*###", "#####.###", "####..###", "*..#.####", "##.....##", "####.#..*", "###..####", "###.#####", "###*#####"],
    colors: ["RRRRRBRRR", "RRRRRBRRR", "RRRRBBRRR", "BBBRBRRRR", "RRBBRBBRR", "RRRRBRBBB", "RRRBBRRRR", "RRRBRRRRR", "RRRBRRRRR"],
    robotRow: 4,
    robotCol: 4,
    robotDir: 0,
    subLengths: [7, 7, 0, 0, 0],
  },
  {
    id: 42,
    title: "The powers",
    about: "",
    author: "igoro",
    items: ["*********", "*#######*", "*#######*", "*#######*", ".********"],
    colors: ["BBBBBBBBB", "BRRRRRRRB", "BRRRRRRRB", "BRRRRRRRB", "BBBBBBBBB"],
    robotRow: 4,
    robotCol: 0,
    robotDir: 0,
    subLengths: [5, 2, 2, 2, 0],
  },
  {
    id: 43,
    title: "Do while",
    about: "",
    author: "igoro",
    items: ["####*#####", "####.#####", "####.#####", "*........*", "####*#####"],
    colors: ["RRRRBRRRRR", "RRRRRRRRRR", "RRRRRRRRRR", "BRRRBRRRRB", "RRRRBRRRRR"],
    robotRow: 3,
    robotCol: 4,
    robotDir: 0,
    subLengths: [10, 2, 0, 0, 0],
  },
  {
    id: 44,
    title: "Convergence",
    about: " ",
    author: null,
    items: ["...............*", "*.............*.", ".*...........*..", "..*.........*...", "...*.......*....", "....*.....*.....", "***********.....", "....*......*....", "...*........*...", "..*..........*..", ".*............*.", "*..............*"],
    colors: ["BRRRRRRRRRRRRRRB", "BRRRRRRRRRRRRRBR", "RBRRRRRRRRRRRBRR", "RRBRRRRRRRRRBRRR", "RRRBRRRRRRRBRRRR", "RRRRBRRRRRBRRRRR", "RRRRRRRRRRGRRRRR", "RRRRBRRRRRRBRRRR", "RRRBRRRRRRRRBRRR", "RRBRRRRRRRRRRBRR", "RBRRRRRRRRRRRRBR", "BRRRRRRRRRRRRRRB"],
    robotRow: 0,
    robotCol: 0,
    robotDir: 0,
    subLengths: [4, 2, 2, 0, 0],
  },
  {
    id: 45,
    title: "Around We Go 1",
    about: "",
    author: "crpietschmann",
    items: ["....*", ".###.", ".###.", ".###.", "*...*"],
    colors: ["BBBBB", "BRRRB", "BRRRB", "BRRRB", "BBBBB"],
    robotRow: 0,
    robotCol: 0,
    robotDir: 1,
    subLengths: [10, 10, 0, 0, 0],
  },
  {
    id: 46,
    title: "Around We Go 2",
    about: "",
    author: "crpietschmann",
    items: ["*.............*", ".##############", ".#*...........*", ".#.###########.", ".#.#*.......*#.", ".#.#.#######.#.", ".#.#########.#.", ".#*.........*#.", ".#############.", "*.............*"],
    colors: ["GBBBBBBBBBBBBBB", "BRRRRRRRRRRRRRR", "BRGBBBBBBBBBBBG", "BRBRRRRRRRRRRRB", "BRBRGBBBBBBBGRB", "BRBRBRRRRRRRBRB", "BRBRRRRRRRRRBRB", "BRGBBBBBBBBBGRB", "BRRRRRRRRRRRRRB", "GBBBBBBBBBBBBBG"],
    robotRow: 5,
    robotCol: 4,
    robotDir: 3,
    subLengths: [4, 0, 0, 0, 0],
  },
  {
    id: 48,
    title: "Up And Down",
    about: "Red Right - Green Left",
    author: "crpietschmann",
    items: ["...*.#####", "..*..#####", ".*.*.#####", "..*..##..*", ".*.*.##...", "..*..##.*.", ".*.*.*.*..", "####..*.*.", "####.*.*..", "####..*.*."],
    colors: ["RRRRGRRRRR", "RBBBGRRRRR", "RBBBGRRRRR", "RBBBGRRRRB", "RBBBGRRRBG", "RBBBGRRRBG", "GGGGBRRRBG", "RRRRRBBBBG", "RRRRRBBBBG", "RRRRRGGGGG"],
    robotRow: 1,
    robotCol: 1,
    robotDir: 1,
    subLengths: [5, 2, 2, 0, 0],
  },
  {
    id: 49,
    title: "Christmas Quilt",
    about: "Look at the colors",
    author: "crpietschmann",
    items: ["................", "................", "..*...*..*..*...", "................", ".*..*..*..*..*..", "................", "..*..*..*..*..*.", "................", "..*.*..*..*..*..", "................", ".*..*..*..*.....", "................"],
    colors: ["RGRGRGRGRGRGRGRG", "GRGRGRGRGRGRGRGR", "RGBBBBBBBBBBBBRG", "GBRGRGRGRGRGRGBR", "RGBBBBBBBBBBBBRG", "GBGRGRGRGRGRGRBR", "RGBBBBBBBBBBBBRG", "GBRGRGRGRGRGRGBR", "RGBBBBBBBBBBBBRG", "GBGRGRGRGRGRGRGR", "RGBBBBBBBBBBBBRG", "GRGRGRGRGRGRGRGR"],
    robotRow: 10,
    robotCol: 13,
    robotDir: 2,
    subLengths: [5, 2, 0, 0, 0],
  },
  {
    id: 50,
    title: "Where does this path lead to",
    about: "Figure the path to the star",
    author: "avatare",
    items: ["...............", ".#########.....", ".#########.###.", "......*....###.", ".#############.", ".#############.", ".........#####.", ".#######.#####.", "...............", ".#######.#####.", ".#######.#####.", "..............."],
    colors: ["GBBBBBBBBBBBBBB", "BRRRRRRRRRGBBBR", "BRRRRRRRRRBRRRB", "BBBBBBBBBBRRRRB", "BRRRRRRRRRRRRRB", "BRRRRRRRRRRRRRG", "RBBBBBBBBRRRRRB", "BRRRRRRRBRRRRRB", "GBBBBBBBBBBBBBG", "BRRRRRRRBRRRRRB", "BRRRRRRRBRRRRRB", "BBBBBBBBBBBBBBB"],
    robotRow: 6,
    robotCol: 8,
    robotDir: 2,
    subLengths: [3, 5, 0, 0, 0],
  },
  {
    id: 51,
    title: "Cartwheel",
    about: "Recursion is a piece of cake.",
    author: "stingray",
    items: ["####.*..####", "###...#..###", "##..#.##*.##", "#.*##.###..#", "..###*####..", ".####..*...*", "*...*..####.", "..####*###..", "#..###.##*.#", "##.*##.#..##", "###..#...###", "####..*.####"],
    colors: ["RRRRGRGGRRRR", "RRRGGBRGGRRR", "RRGGRBRRGGRR", "RGGRRBRRRGGR", "GGRRRBRRRRGG", "GRRRRRRBBBBR", "RBBBBRRRRRRG", "GGRRRRBRRRGG", "RGGRRRBRRGGR", "RRGGRRBRGGRR", "RRRGGRBGGRRR", "RRRRGGRGRRRR"],
    robotRow: 5,
    robotCol: 6,
    robotDir: 0,
    subLengths: [2, 7, 7, 2, 0],
  },
  {
    id: 52,
    title: "Stairways to Heaven",
    about: "",
    author: "splattne",
    items: ["########*", "#######..", "######..#", "#####..##", "####..###", "###..####", "##..#####", "#..######", "..#######"],
    colors: ["RRRRRRRRB", "RRRRRRRBB", "RRRRRRBBR", "RRRRRBBRR", "RRRRBBRRR", "RRRBBRRRR", "RRBBRRRRR", "RBBRRRRRR", "BBRRRRRRR"],
    robotRow: 8,
    robotCol: 0,
    robotDir: 0,
    subLengths: [2, 4, 0, 0, 0],
  },
  {
    id: 53,
    title: "Branches",
    about: "",
    author: "igoro",
    items: ["#########*####", "*.........####", "#.#######.####", "#*####*##.####", "######.##.####", "###*...##.##*#", "######.##.#*.#", "###*##.##.##.#", "###.##.##.##.#", "###.##.##.##.#", "#............*"],
    colors: ["RRRRRRRRRGRRRR", "GRBBBBBBBRRRRR", "RBRRRRRRRBRRRR", "RGRRRRGRRBRRRR", "RRRRRRBRRBRRRR", "RRRGBBRRRBRRGR", "RRRRRRBRRBRGRR", "RRRGRRBRRBRRBR", "RRRBRRBRRBRRBR", "RRRBRRBRRBRRBR", "RBBRBBRBBRBBRG"],
    robotRow: 10,
    robotCol: 1,
    robotDir: 0,
    subLengths: [5, 5, 5, 0, 0],
  },
  {
    id: 54,
    title: "Too easy",
    about: "",
    author: "czvxbc",
    items: ["##**##", "##**##", "*#****", "*.****", "##**##", "##**##"],
    colors: ["RRBBRR", "RRBBRR", "BRBBBB", "BBBBBB", "RRBBRR", "RRBBRR"],
    robotRow: 3,
    robotCol: 1,
    robotDir: 0,
    subLengths: [5, 5, 5, 0, 0],
  },
  {
    id: 55,
    title: "Zig zig",
    about: "Red means left... no, right... er, left.",
    author: "stingray",
    items: ["####....#######", ".....##...#....", ".########.#.##.", ".#.....#..#.#..", ".#.###.#.##.#.#", "...#...#....#..", "####.#########.", "#....#.......#.", "#.####.#####.#.", "#..#...#...#.#.", "##.#.###.#.#...", "...#.....#*####"],
    colors: ["RRRRRBBGRRRRRRR", "RBBBRRRGBGRRBBG", "BRRRRRRRRBRBRRB", "BRRBBBGRRRRBRRR", "BRBRRRBRBRRBRBR", "GBRRRBRRGBBRRGG", "RRRRBRRRRRRRRRB", "RRBBRRRBBBBBGRB", "RBRRRRBRRRRRBRB", "RGGRRBRRRBGRBRB", "RRBRBRRRBRBRGBR", "BBRRGBBBRRBRRRR"],
    robotRow: 11,
    robotCol: 0,
    robotDir: 0,
    subLengths: [5, 5, 0, 0, 0],
  },
  {
    id: 56,
    title: "Turn on red ;-)",
    about: "",
    author: "igoro",
    items: ["............", ".##########.", ".##########.", ".#.......##.", ".#.#####.##.", ".#....*#.##.", ".#######.##.", ".........##.", "###########.", "###########.", "............"],
    colors: ["RBBBBBBBBBGR", "BRRRRRRRRRRG", "RRRRRRRRRRRB", "BRRGRBRBRRRB", "BRGRRRRRBRRR", "GRRBBBBRBRRB", "BRRRRRRRGRRB", "RBBBBBBGRRRR", "RRRRRRRRRRRB", "RRRRRRRRRRRB", "BBBBRBBBRBGR"],
    robotRow: 10,
    robotCol: 0,
    robotDir: 0,
    subLengths: [5, 5, 0, 0, 0],
  },
  {
    id: 57,
    title: "8x8",
    about: "????????? / Chess-inspired",
    author: "inquirer",
    items: ["....*...", "..*...*.", ".*......", "...*...*", "*....*..", "......*.", ".*...*..", "...*...*"],
    colors: ["GBGBGBGB", "BGBGBGBG", "GBGBGBGB", "BGBGBGBG", "GBGBGBGB", "BGBGBGBG", "GBGBGBGB", "BGBGBGBG"],
    robotRow: 0,
    robotCol: 0,
    robotDir: 1,
    subLengths: [10, 5, 5, 4, 4],
  },
  {
    id: 58,
    title: "Diagonale",
    about: "42",
    author: "mandark",
    items: [".........", ".........", ".........", "..*...*..", "...*.*...", "....*....", ".........", "........."],
    colors: ["BBBBBBBBB", "BRBBBBBRB", "BRRBBBRRB", "BRBRBRBRB", "BRBBRBBRB", "BRBBBBBRB", "BRBBBBBRB", "BBBBBBBBB"],
    robotRow: 7,
    robotCol: 1,
    robotDir: 3,
    subLengths: [5, 5, 0, 0, 0],
  },
  {
    id: 59,
    title: "Recursion",
    about: "... the other recursion !",
    author: "mandark",
    items: ["........***", "########*#*", "########***"],
    colors: ["BBBBBBBBRBB", "RRRRRRRRBRB", "RRRRRRRRBBB"],
    robotRow: 0,
    robotCol: 0,
    robotDir: 0,
    subLengths: [5, 0, 0, 0, 0],
  },
  {
    id: 61,
    title: "Red-Green is the code",
    about: "",
    author: "igoro",
    items: ["#############*", ".............."],
    colors: ["RRRRRRRRRRRRRB", "GGRBGRBBGRRBRG"],
    robotRow: 1,
    robotCol: 0,
    robotDir: 0,
    subLengths: [8, 0, 0, 0, 0],
  },
  {
    id: 62,
    title: "Red green is the code II",
    about: "Same thing, less memory",
    author: "czvxbc",
    items: ["###############*", "................"],
    colors: ["RRRRRRRRRRRRRRRB", "BRBGGRBBGRRRBGRG"],
    robotRow: 1,
    robotCol: 0,
    robotDir: 0,
    subLengths: [5, 0, 0, 0, 0],
  },
  {
    id: 63,
    title: "Humm..",
    about: "Which way",
    author: "monkeyfarts",
    items: ["##..##", "#.*..#", "....*.", ".*.*..", "#*.**#", "##..##"],
    colors: ["RRGBRR", "RBRGBR", "BGBBRG", "GRBBGB", "RBGRBR", "RRBGRR"],
    robotRow: 3,
    robotCol: 2,
    robotDir: 0,
    subLengths: [4, 3, 0, 0, 0],
  },
  {
    id: 65,
    title: "Continuations",
    about: "How inefficient!",
    author: "stingray",
    items: ["##...###########", "##.#.####...####", "##.#.###..#.####", "#..#.###.##.#...", "#.##.###.##.#.#.", "#.##.##..##.#.#*", "..##.##.###.#.##", "####..#.###.#.##", "#####.#.###...##", "#####.#.########", "#####...########"],
    colors: ["RRRBRRRRRRRRRRRR", "RRBRBRRRRRBRRRRR", "RRBRBRRRRRRBRRRR", "RRRRBRRRBRRBRRBR", "RBRRBRRRBRRBRBRB", "RBRRBRRRRRRBRBRB", "BRRRBRRBRRRBRBRR", "RRRRRRRBRRRBRBRR", "RRRRRBRBRRRRBRRR", "RRRRRBRBRRRRRRRR", "RRRRRRBRRRRRRRRR"],
    robotRow: 6,
    robotCol: 0,
    robotDir: 0,
    subLengths: [2, 2, 2, 2, 0],
  },
  {
    id: 66,
    title: "Reflection",
    about: "Play the first half, then rewind.",
    author: "stingray",
    items: ["..*######", "*...*####", "*.*######", "*.......*", "*.....*##", "*.*######", "*.*######", "*.....*##", "*.......*", "*.*######", "*...*####", "*.*######"],
    colors: ["RBRRRRRRR", "RBBBRRRRR", "RBRRRRRRR", "RBBBBBBBR", "RBBBBBRRR", "RBRRRRRRR", "BBBRRRRRR", "BBBBBBBRR", "BBBBBBBBB", "BBBRRRRRR", "BBBBBRRRR", "BBBRRRRRR"],
    robotRow: 0,
    robotCol: 0,
    robotDir: 0,
    subLengths: [4, 5, 4, 4, 4],
  },
  {
    id: 67,
    title: "Pathway",
    about: "",
    author: "tisba",
    items: [".....##########", "####.##########", "####.##########", "####.##########", "####.##########", "####.###*..####", "####.....#.#..*", "##########...##"],
    colors: ["GGGGRRRRRRRRRRR", "RRRRGRRRRRRRRRR", "RRRRGRRRRRRRRRR", "RRRRGRRRRRRRRRR", "RRRRGRRRRRRRRRR", "RRRRGRRRRGRRRRR", "RRRRBGGGBRGRRGG", "RRRRRRRRRRBGBRR"],
    robotRow: 0,
    robotCol: 0,
    robotDir: 0,
    subLengths: [4, 0, 0, 0, 0],
  },
  {
    id: 69,
    title: "Arrows",
    about: "Follow the green arrows",
    author: "amazed",
    items: ["#............#", "..............", "............*.", "..............", "..............", "..............", "..............", "..............", "..............", "#............#"],
    colors: ["RBBBBBBBBBBBBR", "BRBBBBBBGRBBBB", "BGBBBBRGBBBBBB", "BBBBBBBBBGBBBB", "BBBBRGBBBRBBBB", "BRGBBBBBBBBRBB", "BBBBBBBBBBBGBB", "BBBBGBGBBBBBBB", "BBBBRBRBBBGRBB", "RBBBBBBBBBBBBR"],
    robotRow: 8,
    robotCol: 1,
    robotDir: 0,
    subLengths: [3, 6, 0, 0, 0],
  },
  {
    id: 70,
    title: "USSR",
    about: "",
    author: "nondead",
    items: ["................", "...*....**......", "..........*.....", "......***..*....", ".....***....*...", "....****....*...", ".....*.**...*...", "........**.*....", ".....*...**.....", "....*.******....", "...*.......**...", "................"],
    colors: ["BBBBBBBBBBBBBBBB", "BRRRRRRRRRRRRRRB", "BRRRRRRRRRRRRRRB", "BRRRRRRRRRRRRRRB", "BRRRRRRRRRRRRRRB", "BRRRRRRRRRRRRRRB", "GRRRRRRRRRRRRRRG", "GRRRRRRRRRRRRRRG", "GRRRRRRRRRRRRRRG", "GRRRRRRRRRRRRRRG", "GRRRRRRRRRRRRRRG", "GGGGGGGGGGGGGGGG"],
    robotRow: 11,
    robotCol: 0,
    robotDir: 0,
    subLengths: [4, 10, 0, 0, 0],
  },
  {
    id: 72,
    title: "One star",
    about: "",
    author: "glum",
    items: ["#............#", ".#########..*.", ".########.....", ".#######....#.", ".######....##.", "..........###.", "#............#"],
    colors: ["RBBBBBBBBBBBBR", "BRRRRRRRRRBGRB", "BRRRRRRRRBGRBB", "BRRRRRRRBGRBRB", "BRRRRRRBGRBRRB", "BBBBBBBBRBRRRB", "RBBBBBBBBBBBBR"],
    robotRow: 5,
    robotCol: 1,
    robotDir: 2,
    subLengths: [4, 5, 0, 0, 0],
  },
  {
    id: 74,
    title: "Knight",
    about: "",
    author: "stingray",
    items: ["########....##", "....####.##...", ".##...##.####*", ".####.##...###", "...##.###.####", "#.##...#..####", "#.####...#####", "########.#####"],
    colors: ["RRRRRRRRBGBBRR", "BGBBRRRRBRRBBB", "BRRBBBRRGRRRRB", "GRRRRGRRBBRRRR", "BBRRRBRRRBRRRR", "RBRRRBBRBBRRRR", "RBRRRRBBBRRRRR", "RRRRRRRRRRRRRR"],
    robotRow: 6,
    robotCol: 1,
    robotDir: 3,
    subLengths: [8, 0, 0, 0, 0],
  },
  {
    id: 75,
    title: "Tetris",
    about: "The solution should just fall into place...",
    author: "stingray",
    items: ["###..#######.###", "##..#######.*.##", ".#####.#.###..##", "..##......###..#", "..........###..#", "#.#.#...........", "#...##..........", "#...#........#..", "................", "#...............", ".....#.........."],
    colors: ["RRRBBRRRRRRRRRRR", "RRBBRRRRRRRRRRRR", "RRRRRRGRBRRRBBRR", "RRRRGGGBBGRRRBBR", "RGGGRRRBRGRRRGRR", "RGRBRRBRRGGBBGRR", "RGBBRRBBRRBBGGRB", "RGBRRGRBRRRBBRBB", "GGRRRGRRGGGRBBBG", "RBBRGGRBBRGRRBBG", "BBRRRRBBRRRRBBGG"],
    robotRow: 10,
    robotCol: 0,
    robotDir: 0,
    subLengths: [4, 0, 0, 0, 0],
  },
  {
    id: 76,
    title: "Count the tiles",
    about: "",
    author: "igoro",
    items: ["##.............", "##.###########.", "##*###########.", "##############.", "###..........#.", "###.########.#.", "###.########...", "###.###########", "###.....#######", "#######.#######", "........#######"],
    colors: ["RRRBRBBBBRBBBBR", "RRBRRRRRRRRRRRB", "RRBRRRRRRRRRRRB", "RRRRRRRRRRRRRRB", "RRRRBBBBRBBBRRB", "RRRBRRRRRRRRBRB", "RRRBRRRRRRRRRBR", "RRRBRRRRRRRRRRR", "RRRRBBBRRRRRRRR", "RRRRRRRBRRRRRRR", "RBBBBRBRRRRRRRR"],
    robotRow: 10,
    robotCol: 0,
    robotDir: 0,
    subLengths: [3, 3, 0, 0, 0],
  },
  {
    id: 77,
    title: "Two techniques",
    about: "Combine two methods from previous puzzles",
    author: "drus",
    items: ["###........*.#", "##...*........", "#.............", "..............", "..............", "...*........*.", "..............", ".....*.......#", "............##", "#........*.###"],
    colors: ["RRRBBRRBBBBBBR", "RRBBRBBGBRBRBB", "RBBBBRRRBBGBRB", "BBRBBBBBBBGBRB", "BGGGGBBBBBBRBB", "BBRRRBBBBBBBBB", "BRBBBGGBBBBBBB", "BBBBRBBBBBBBBR", "BBBRRBBBBBBBRR", "RBBBBBBBBGBRRR"],
    robotRow: 8,
    robotCol: 0,
    robotDir: 0,
    subLengths: [4, 6, 4, 4, 0],
  },
  {
    id: 78,
    title: "Easy Recursion",
    about: "fun stuff",
    author: "hidn",
    items: ["#*####*#", "********", "#******#", "#******#", "#******#", "#******#", ".*******", "#*####*#"],
    colors: ["RGRRRRGR", "GRRRRRRG", "RRBBBBRR", "RRBBBBRR", "RRBBBBRR", "RRBBBBRR", "GRRRRRRG", "RGRRRRGR"],
    robotRow: 6,
    robotCol: 0,
    robotDir: 0,
    subLengths: [10, 10, 5, 3, 5],
  },
  {
    id: 80,
    title: "RRB, RRG",
    about: "",
    author: "igoro",
    items: ["..............", ".############.", ".############.", ".##...........", ".##*##########", ".#############", ".............#", "############.#", "############.#", ".............#"],
    colors: ["GGGGGGGGGGGRRG", "RRRRRRRRRRRRRR", "RRRRRRRRRRRRRR", "BRRBRRBBBBBBBG", "BRRBRRRRRRRRRR", "BRRRRRRRRRRRRR", "GRRGRBRGRBGGBR", "RRRRRRRRRRRRRR", "RRRRRRRRRRRRRR", "BBGGBBGGBBRRBR"],
    robotRow: 9,
    robotCol: 0,
    robotDir: 0,
    subLengths: [3, 3, 3, 0, 0],
  },
  {
    id: 81,
    title: "Find a way",
    about: "",
    author: "seka",
    items: ["...........***..", ".........*......", "..........*.....", ".....*......*...", "......*.......*.", "........**......", "..*.....*.......", "....*...........", "..........*..*..", "................", "......*.........", "................"],
    colors: ["BRGBRBBBBBGBBBGB", "BBBBBBGBBBBBGBBB", "BGBBGRBBBGBBBBBB", "GBRBBBBBRBBBBGBB", "BGBGBRBGBBRBBRBB", "RRBBRBBBBBBBGBBG", "GBBBBBBGBBBRBBBB", "BGBRBRBGBGBGBGBB", "BBBBBBGBBBBBBBGB", "RBBRBBRBBBGBBBRB", "BBBBRBBBRBRBBBBB", "BBBBBBBGBBBBRBBR"],
    robotRow: 11,
    robotCol: 1,
    robotDir: 3,
    subLengths: [4, 4, 0, 0, 0],
  },
  {
    id: 82,
    title: "One Star 2",
    about: "It's easy too...",
    author: "glum",
    items: ["#............#", ".#########..*.", ".########.....", ".#######....#.", ".######....##.", "..........###.", "#............#"],
    colors: ["RGGGGGGGGGGGGR", "GRRRRRRRRRGGBG", "GRRRRRRRRGGRGG", "GRRRRRRRGGRGRG", "GRRRRRRGGRGRRG", "GGGGGGGGRGRRRG", "RGGGGGGGGGGGGR"],
    robotRow: 5,
    robotCol: 1,
    robotDir: 2,
    subLengths: [4, 5, 0, 0, 0],
  },
  {
    id: 83,
    title: "Factors of 2",
    about: "The name gives it away....",
    author: "hidn",
    items: ["#####*....", "#####.###.", "*.....###.", "#########.", "#########.", "#########.", "###.*....."],
    colors: ["RRRRRGGGGR", "RRRRRBRRRR", "RRRRRBRRRR", "RRRRRRRRRR", "RRRRRRRRRR", "RRRRRRRRRR", "RRRBBRRRRR"],
    robotRow: 6,
    robotCol: 3,
    robotDir: 0,
    subLengths: [10, 0, 0, 0, 0],
  },
  {
    id: 84,
    title: "Simple spiral",
    about: "",
    author: "igoro",
    items: ["....#", ".##.#", ".#..#", ".####", "....*"],
    colors: ["BBBBR", "BRRBR", "BRBBR", "BRRRR", "BBBBB"],
    robotRow: 2,
    robotCol: 2,
    robotDir: 0,
    subLengths: [5, 2, 2, 2, 2],
  },
  {
    id: 85,
    title: "Less or more?",
    about: "",
    author: "igoro",
    items: ["......#.....###.", ".####.#.###.###.", ".####.#.###.###.", ".####.#.###.###.", ".####.#.###.###.", "...*#.#.###.....", "#####.#.########", "......#.........", ".##############.", ".##############.", ".##############.", "................"],
    colors: ["BRGGGBRBRGGBRRRB", "GRRRRRRGRRRRRRRG", "GRRRRRRGRRRGRRRR", "GRRRRGRGRRRGRRRR", "RRRRRGRGRRRGRRRR", "BGGGRGRGRRRBRRGB", "RRRRRGRRRRRRRRRR", "BGGGRBRBGGRRRRRB", "RRRRRRRRRRRRRRRG", "RRRRRRRRRRRRRRRR", "GRRRRRRRRRRRRRRR", "BRRRRRRRRRRGGGGB"],
    robotRow: 0,
    robotCol: 15,
    robotDir: 1,
    subLengths: [5, 5, 5, 0, 0],
  },
  {
    id: 86,
    title: "Bob's game",
    about: " ",
    author: null,
    items: ["###*....", "#######.", "#######.", "....###.", ".##.###.", ".##.....", "....####"],
    colors: ["RRRBBBBB", "RRRRRRRG", "RRRRRRRG", "BBBBRRRG", "BRRBRRRG", "BRRRRRRG", "BBBBRRRR"],
    robotRow: 5,
    robotCol: 0,
    robotDir: 0,
    subLengths: [10, 9, 5, 0, 0],
  },
  {
    id: 87,
    title: "Red run",
    about: "All work and no play...",
    author: null,
    items: ["...............", "#############.#", "#############.#", "###.#########.#", "###........##.#", "###.#####.###.#", "###.####*.###.#", "###.#####.###.#", "###.#########.#", "###.#########.#", "##............#", "#############.#"],
    colors: ["BBBBBBBGGGGGGGG", "RRRRRRRRRRRRRBR", "RRRRRRRRRRRRRBR", "RRRGRRRRRRRRRBR", "RRRGBBBGGGGRRBR", "RRRGRRRRRBRRRBR", "RRRGRRRRRGRRRGR", "RRRBRRRRRGRRRGR", "RRRBRRRRRRRRRGR", "RRRBRRRRRRRRRGR", "RRGGGGGGBBBBBGR", "RRRRRRRRRRRRRGR"],
    robotRow: 0,
    robotCol: 0,
    robotDir: 0,
    subLengths: [5, 3, 0, 0, 0],
  },
  {
    id: 88,
    title: "Incomplete grid",
    about: "",
    author: "igoro",
    items: ["########*#*####", "########.#.####", "##*###*.....*##", "##.#####.#.####", "*...*#*...*#*##", "##.#.#.#.#.#.##", "*.............*", "##.#.#.#.#.#.##", "*...*#*...*#*##", "##.#####.######", "##*###*...*####"],
    colors: ["RRRRRRRRBRBRRRR", "RRRRRRRRBRBRRRR", "RRBRRRBBGBGBBRR", "RRBRRRRRBRBRRRR", "BBGBBRBBGBBRBRR", "RRBRBRBRBRBRBRR", "BBGBGBGBGBGBGBB", "RRBRBRBRBRBRBRR", "BBGBBRBBGBBRBRR", "RRBRRRRRBRRRRRR", "RRBRRRBBGBBRRRR"],
    robotRow: 10,
    robotCol: 8,
    robotDir: 3,
    subLengths: [5, 5, 10, 0, 0],
  },
  {
    id: 90,
    title: "Without blue",
    about: "4 identical path",
    author: "glum",
    items: ["..*...*.....***.", "................", ".*..........*..*", ".......*......*.", ".....*....*.....", ".....*..........", "....*...........", ".........*.*..*.", "..*..*......*...", "*.....*...*....*", "...*...........*", "..**....*..*...."],
    colors: ["RGRRRRRRRGRRGRRG", "RRRRRRRRRRRRRRRR", "RRRRRRRRRRRRRRRR", "RGRRRRRRRRRRRRGR", "RRRRRGRRRRRRRRRG", "RRRRRRRRRRRRRRRR", "RRRGRRRRGRRRRRRR", "RRRRRRRRRGRRGRRR", "GRRRRRRRRRRRRRGR", "RRRRRGRRRRRRRRRG", "RRRRRRRRRRRRRRRR", "GRRGRRRRGRRRRRRG"],
    robotRow: 11,
    robotCol: 0,
    robotDir: 0,
    subLengths: [2, 5, 3, 3, 0],
  },
  {
    id: 91,
    title: "Dangerous Maze",
    about: "Explore the whole maze, but watch out for potholes!",
    author: "recursive",
    items: ["#***######***###", "********#******#", "***#*****##*****", "***#*#****#***##", "***************#", "****************", "******#***###***", "****************", "#***###********#", "*****#****##****", "****************", "********.*******"],
    colors: ["RGGGRRRRRRGGGRRR", "GBBBGGGGRGBBBGGR", "GBGRGBBBGRRGBBBG", "GBGRGRGBBGRGBGRR", "GBGGBGGGBGGGBGGR", "GBGGBBBGBGBBBBBG", "GBGGBGRGBGRRRGBG", "GBBBBBGGBGGGGBBG", "RGBGRRRGBBBBGBGR", "GBBGGRGGBGRRGBBG", "GBGGBGBGBGGGGGBG", "GBBBBBBBBBBBBBBG"],
    robotRow: 11,
    robotCol: 8,
    robotDir: 3,
    subLengths: [10, 10, 10, 5, 0],
  },
  {
    id: 92,
    title: "king's way",
    about: "",
    author: "evko",
    items: ["...............*", "................", "................", "................", "................", "...............#", "..............##", ".............###", "............####", "...........#####", "..........######", ".........#######"],
    colors: ["RBBBBBBBBBBBBBBB", "RBBBBBBBBBBBBBBB", "RBBBBBBBBBBBBBBB", "RBBBBBBBBBBBBBBB", "RBBBBBBBBBBBBBBG", "RBBBBBBBBBBBBBGR", "RBBBBBBBBBBBBGRR", "RBBBBBBBBBBBGRRR", "RBBBBBBBBBBGRRRR", "RBBBBBBBBBGRRRRR", "RBBBBBBBBGRRRRRR", "RBBBBBBBGRRRRRRR"],
    robotRow: 11,
    robotCol: 0,
    robotDir: 3,
    subLengths: [3, 2, 6, 0, 0],
  },
  {
    id: 93,
    title: "Fly in the sky",
    about: "simple recursion, hard path",
    author: "evko",
    items: ["...............", ".........##....", "........###....", ".......#.......", "......#.*..*...", ".....#..*..*...", "......#.*..*...", ".......#.......", "........###....", ".........##....", "..............."],
    colors: ["BBBBBBBBGBBBBBB", "BBBBBBBBGRRBBBB", "BBBBBBBGRRRBBBB", "BBBBBBBRBBBGBBB", "BBBBBBRGBBBBBBB", "BBBBBRBGBBBBBBB", "BBBBBBRGBBBBBBB", "BBBBBBBRBBBGBBB", "BBBBBBBGRRRBBBB", "BBBBBBBBGRRBBBB", "BBBBBBBBGBBBBBB"],
    robotRow: 5,
    robotCol: 0,
    robotDir: 0,
    subLengths: [10, 0, 0, 0, 0],
  },
  {
    id: 94,
    title: "Treasure Hunters",
    about: "Variation on \"Reflection\" theme",
    author: "evko",
    items: ["#.....#***#", "....#.#****", "..#.#.#*#**", "....#.#****", ".####.####*", ".####******"],
    colors: ["RRGGGRRBBBR", "RGGRRGRBBBB", "GGRGRGRBRBB", "GRGRRGRBBBB", "GRRRRGRRRRB", "RRRRRBBBBBB"],
    robotRow: 5,
    robotCol: 0,
    robotDir: 3,
    subLengths: [6, 0, 0, 0, 0],
  },
  {
    id: 95,
    title: "Complex elevation",
    about: "Understanding C++ recursion mechanics",
    author: "inquirer",
    items: ["######*###", "######..##", "#######..#", "###.####..", "##...##..#", "#..#....##", "..###..###"],
    colors: ["RRRRRRBRRR", "RRRRRRBBRR", "RRRRRRRBBR", "RRRGRRRRBB", "RRRBGRRBBR", "RRBRBGBBRR", "RBRRRBBRRR"],
    robotRow: 6,
    robotCol: 0,
    robotDir: 3,
    subLengths: [8, 4, 7, 2, 2],
  },
  {
    id: 96,
    title: "Convex shape",
    about: "",
    author: "igoro",
    items: ["###..........#", "##.**********.", "#.***********.", ".************.", ".************.", ".************.", ".***.********.", ".************.", "#.**********.#", "##..........##"],
    colors: ["RRRRRRRRRRRRRR", "RRRBBBBBBBBBBR", "RRBBBBBBBBBBBR", "RBBBBBBBBBBBBR", "RBBBBBBBBBBBBR", "RBBBBBBBBBBBBR", "RBBBBBBBBBBBBR", "RBBBBBBBBBBBBR", "RRBBBBBBBBBBRR", "RRRRRRRRRRRRRR"],
    robotRow: 6,
    robotCol: 4,
    robotDir: 0,
    subLengths: [5, 5, 5, 0, 0],
  },
  {
    id: 97,
    title: "Smart lemma",
    about: "clear math, no hacker's features :)",
    author: "evko",
    items: ["*........*", ".########.", ".*.....*#.", "..#####.#.", "..*..*#.#.", "...##.#.#.", "...##.#.#.", "..*..*#.#.", ".......*#.", ".........*"],
    colors: ["BBBBBBBBBB", "BRRRRRRRRB", "BGGGGGGGRB", "BGRRRRRGRB", "BGRRRRRGRB", "BGRRRRRGRB", "BGRRRRRGRB", "BRRRRRRGRB", "GGGGGGGGRB", "BBBBBBBBBB"],
    robotRow: 9,
    robotCol: 0,
    robotDir: 0,
    subLengths: [3, 4, 4, 4, 0],
  },
  {
    id: 98,
    title: "Fly in the sky II",
    about: "",
    author: "evko",
    items: ["*....*....*....*", "................", "................", "................", "................", "*.........*....*", "................", "................", "................", "................", "*....*....*....*"],
    colors: ["BBBBBBBBBBBBBBBR", "BBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBB", "RBBBBBBBBBBBBBBB"],
    robotRow: 5,
    robotCol: 5,
    robotDir: 0,
    subLengths: [8, 4, 4, 3, 2],
  },
  {
    id: 100,
    title: "3-2-1... Start!",
    about: "",
    author: "evko",
    items: ["................", "................", "................", "...........#....", "...........#....", "...........#....", "...........#....", "...........#....", "...........#....", "..*........#....", "############....", "................"],
    colors: ["BBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBB", "BBBBBBBBBBBRBBBB", "BBBBBBBBBBBRBBBB", "BBBBBBBBBBBRBBBB", "BBBBBBBBBBBRBBBB", "BBBBBBBBBBBRBBBB", "BBBBBBBBBBBRBBBB", "BBBBBBBBBBBRBBBB", "RRRRRRRRRRRRBBBB", "RGGRGGRGGRGGRGGR"],
    robotRow: 11,
    robotCol: 0,
    robotDir: 0,
    subLengths: [4, 3, 2, 2, 0],
  },
];
